standarized_developer_type_column = {
    # 2017
    "Web developer": "Web developer",
    "Desktop applications developer": "Developer, desktop or enterprise applications",
    "Mobile developer": "Developer, mobile",
    "Full stack Web developer": "Developer, full-stack",
    "Database administrator": "Database administrator",
    "Other": "Other",
    # merge ds-ml into one feature
    "Data scientist": "Data scientist",
    "Machine learning specialist": "Machine learning specialist",
    "Developer with a statistics or mathematics background": "Developer with a statistics or mathematics background",
    "Systems administrator": "System administrator",
    "DevOps specialist": "DevOps specialist",
    "Embedded applications/devices developer": "Embedded applications/devices developer",
    "Back-end Web developer": "Developer, back-end",
    "Analyst or consultant": "Analyst or consultant",
    "Graphics programming": "Graphics programming",
    "Graphic designer": "Graphic designer",
    "Front-end Web developer": "Developer, front-end",
    "Quality assurance engineer": "Quality assurance engineer",
    "Educator or academic": "Educator or academic",
    "Designer or illustrator": "Designer or illustrator",
    "Product manager": "Product manager",
    "C-suite executive": "C-suite executive",
    "Marketing or sales manager": "Marketing or sales professional",
    "Elected official": "Elected official",

    # 2018
    "Back-end developer": "Developer, back-end",
    "Full-stack developer": "Developer, full-stack",
    "Front-end developer": "Developer, front-end",
    "Mobile developer": "Developer, mobile",
    "Desktop or enterprise applications developer": "Developer, desktop or enterprise applications",
    "Student": "Student",
    "Database administrator": "Database administrator",
    "Designer": "Designer",
    "System administrator": "System administrator",
    "DevOps specialist": "DevOps specialist",
    "Data or business analyst": "Data or business analyst",
    "Data scientist or machine learning specialist": "Data scientist or machine learning specialist",
    "QA or test developer": "QA or test developer",
    "Engineering manager": "Engineering manager",
    "Embedded applications or devices developer": "Embedded applications or devices developer",
    "Game or graphics developer": "Game or graphics developer",
    "Product manager": "Product manager",
    "Educator or academic researcher": "Educator or academic researcher",
    "C-suite executive (CEO, CTO, etc.)": "C-suite executive (CEO, CTO, etc.)",
    "Marketing or sales professional": "Marketing or sales professional",

    # 2019
    "Developer, full-stack": "Developer, full-stack",
    "Developer, back-end": "Developer, back-end",
    "Developer, front-end": "Developer, front-end",
    "Developer, desktop or enterprise applications": "Developer, desktop or enterprise applications",
    "Developer, mobile": "Developer, mobile",
    "Student": "Student",
    "Database administrator": "Database administrator",
    "Designer": "Designer",
    "System administrator": "System administrator",
    "DevOps specialist": "DevOps specialist",
    "Developer, embedded applications or devices": "Developer, embedded applications or devices",
    "Data scientist or machine learning specialist": "Data scientist or machine learning specialist",
    "Developer, QA or test": "Developer, QA or test",
    "Data or business analyst": "Data or business analyst",
    "Academic researcher": "Academic researcher",
    "Educator": "Educator",
    "Engineer, data": "Engineer, data",
    "Developer, game or graphics": "Developer, game or graphics",
    "Engineering manager": "Engineering manager",
    "Product manager": "Product manager",
    "Scientist": "Scientist",
    "Engineer, site reliability": "Engineer, site reliability",
    "Senior executive/VP": "Senior executive/VP",
    "Marketing or sales professional": "Marketing or sales professional",

    # 2020
    "Developer, back-end": "Developer, back-end",
    "Developer, full-stack": "Developer, full-stack",
    "Developer, front-end": "Developer, front-end",
    "Developer, desktop or enterprise applications": "Developer, desktop or enterprise applications",
    "Developer, mobile": "Developer, mobile",
    "DevOps specialist": "DevOps specialist",
    "Database administrator": "Database administrator",
    "System administrator": "System administrator",
    "Data scientist or machine learning specialist": "Data scientist or machine learning specialist",
    "Product manager": "Product manager",
    "Marketing or sales professional": "Marketing or sales professional",
    "Academic researcher": "Academic researcher",
    "Educator": "Educator",
    "Designer": "Designer",
    "Developer, embedded applications or devices": "Developer, embedded applications or devices",
    "Data or business analyst": "Data or business analyst",
    "Developer, QA or test": "Developer, QA or test",
    "Engineer, data": "Engineer, data",
    "Developer, game or graphics": "Developer, game or graphics",
    "Engineering manager": "Engineering manager",
    "Scientist": "Scientist",
    "Engineer, site reliability": "Engineer, site reliability",
    "Senior executive/VP": "Senior executive/VP",
}


selected_dev_type_columns = {
    "Developer, back-end": "Backend",
    "Developer, front-end": "Frontend",
    "Developer, full-stack": "Fullstack",
    "Developer, mobile": "Mobile",
    "Developer, desktop or enterprise applications": "Desktop",
    "DevOps specialist": "DevOps",
    "Database administrator": "Database Admin",
    "System administrator": "System Admin",
    "Data scientist or machine learning specialist": "Data Scientist",
    "Data or business analyst": "Data Analyst",
    "Engineering manager": "Engineer Manager",
    "Product manager": "Product manager",
    "Designer": "Designer",
}