tech_labeling = {
    "javascript": "language",
    "java": "language",
    "sql": "language",
    "c": "language",
    "css": "language",
    "php": "language",
    "c++": "language",
    "perl": "language",
    "c#": "language",
    "python": "language",
    "nan": "",
    "ruby": "language",
    "objective-c": "language",
    "html5": "language",
    "jquery": "js",
    "node js": "js",
    "scala": "language",
    "lamp": "tech",
    "redis": "db",
    "go": "language",
    "sql server": "tech",
    "cloud": "tech",
    "mongodb": "db",
    "android": "tech",
    "arduino": "tech",
    "raspberry pi": "tech",
    "angular js": "js tech",
    "windows phone": "tech",
    "ios": "tech",
    "sharepoint": "tech",
    "wordpress": "tech",
    "c++11": "language",
    "coffeescript": "language",
    "clojure": "language",
    "salesforce": "tech",
    "cordova": "tech",
    "r": "language",
    "swift": "language",
    "hadoop": "tech",
    "visual basic": "language",
    "spark": "tech",
    "cassandra": "db",
    "matlab": "language",
    "dart": "language",
    "f#": "language",
    "haskell": "language",
    "rust": "language",
    "react js": "js tech",
    "elixir": "language",
    "erlang": "language",
    "assembly": "language",
    "vb.net": "language",
    "typescript": "language",
    "lua": "language",
    "vba": "language",
    "groovy": "language",
    "smalltalk": "language",
    "visual basic 6": "language",
    "common lisp": "language",
    "julia": "language",
    "hack": "language",
    "html": "language",
    "bash": "language",
    "shell": "language",
    "kotlin": "language",
    "cobol": "language",
    "delphi": "language",
    "object pascal": "language",
    "ocaml": "language",
    "powershell": "tech",
    "webassembly": "language",
    "other(s):": "tech",
    "html/css": "language",
}